# Generated by Django 5.0 on 2024-01-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='post_media/'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url',
            field=models.URLField(default='https://default-media-url.com'),
        ),
    ]
