# Generated by Django 5.0 on 2024-01-02 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_post_media_file_post_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media_file',
            new_name='media',
        ),
    ]
