# Generated by Django 5.0 on 2024-01-03 20:58

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='post_photos/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video1',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='video2',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
