# Generated by Django 5.0 on 2024-01-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_post_photo1_post_photo2_post_video1_post_video2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
