# Generated by Django 5.0 on 2024-01-10 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0023_alter_post_author_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='authored_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
