# Generated by Django 5.0 on 2024-01-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0025_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
