# Generated by Django 4.2.9 on 2024-01-26 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0028_comment_is_private_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateField()),
                ('posts', models.ManyToManyField(to='ads.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
