# Generated by Django 4.2.9 on 2024-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0029_dailynewsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video1',
            new_name='embedded_video',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video2',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
