# Generated by Django 4.2.9 on 2024-01-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0031_rename_photo_post_photo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AddField(
            model_name='post',
            name='media_url1',
            field=models.URLField(default='https://default-media-url.com', verbose_name='Media URL 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_url2',
            field=models.URLField(default='https://default-media-url.com', verbose_name='Media URL 2'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url1',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL 1'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url2',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL 2'),
        ),
    ]
